name: Secret Scan

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  scan-secrets:
    name: Scan for Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run TruffleHog Scan
        uses: trufflesecurity/trufflehog@v3
        with:
          path: "."
          base: "origin/main"  

      - name: Notify on Failure
        if: failure()
        run: |
          echo "🚨 Secret(s) detected! Review the scan results."
          # Add Slack or email alert here if needed
