name: Trufflehog Secret Scan

on:
  push:
    branches:
      - main  # You can change this to any branch you want to monitor

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trufflehog
      id: trufflehog
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        format: json
        fail: true

    - name: Display results
      run: |
        echo "Trufflehog scan results:"
        echo "${{ steps.trufflehog.outputs.results }}"
