name: Secret Scanning

on:
  push:
    branches:
      - main
      - 'feature/*'
    paths:
      - '**/*'

jobs:
  secret_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install truffleHog

      - name: Run TruffleHog to detect secrets
        run: |
          trufflehog filesystem --json . > trufflehog_results.json
          cat trufflehog_results.json
        continue-on-error: true

      - name: Fail if secrets are found
        if: failure()
        run: exit 1
