name: Scan Secrets with TruffleHog

on:
  pull_request:

jobs:
  ScanSecrets:
    name: Secret Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get full history for better scanning
          ref: ${{ github.head_ref }}

      - name: Run TruffleHog Scan
        id: trufflehog
        uses: trufflesecurity/trufflehog@v3.0.6
        continue-on-error: true
        with:
          scanArguments: --regex --entropy=True

      - name: Fail if Secrets are Found
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
