name: TruffleHog Secret Scanning

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is available for scanning

      - name: Run TruffleHog Secret Scanner
        id: trufflehog
        uses: trufflesecurity/trufflehog@v3.0.6
        continue-on-error: true
        with:
          scanArguments: --regex --entropy=True

      - name: Scan Results Status
        if: steps.trufflehog.outcome == 'failure'
        run: exit 1
